### ISSUE TITLE
Error during docker-compose up

### ISSUE THREAD

**Issue by atos93** [ghorbani-mohammad/shop-youtube-tutorial#6]
Hello, I'm getting and error during `docker-compose up`

`ERROR: The Compose file './docker-compose.yml' is invalid because:`
`Unsupported config option for volumes: 'shop_db'`
`Unsupported config option for services: 'shop_worker'`

**Comment by moo-gh** [comment]
Hi @atos93 
I just checked the master branch and didn't get your mentioned errors. Please pull from the master branch one again and check it.
